services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  
  postgres:
    image: postgres:13.4
    container_name: postgres
    healthcheck:
      test: pg_isready -U ${DB_USER} -h 127.0.0.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db:
